// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type RecordStatus string 

const (
	RecordStatusAppstatusActive   RecordStatus = "app.status.Active"
	RecordStatusAppstatusInactive RecordStatus = "app.status.Inactive"
	RecordStatusAppstatusBlocked  RecordStatus = "app.status.Blocked"
	RecordStatusValue3            RecordStatus = ""
)

func (e *RecordStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RecordStatus(s)
	case string:
		*e = RecordStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RecordStatus: %T", src)
	}
	return nil
}

type NullRecordStatus struct {
	RecordStatus RecordStatus `json:"recordStatus"`
	Valid        bool         `json:"valid"` // Valid is true if RecordStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRecordStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RecordStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RecordStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRecordStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RecordStatus), nil
}

type Connection struct {
	ID           int64            `json:"id"`
	ConnectionID sql.NullString   `json:"connection_id"`
	AccountID    int64            `json:"account_id"`
	UserID       int64            `json:"user_id"`
	CreateDate   sql.NullTime     `json:"create_date"`
	LastUpdate   time.Time        `json:"last_update"`
	RecordStatus NullRecordStatus `json:"record_status"`
	Active       RecordStatus     `json:"active"`
	Connected    sql.NullString   `json:"“connected”"`
	Disconnected sql.NullString   `json:"“disconnected”"`
	UserData     sql.NullString   `json:"user_data"`
	AccountData  sql.NullString   `json:"account_data"`
	AuthMenu     sql.NullString   `json:"auth_menu"`
	AuthKeys     sql.NullString   `json:"auth_keys"`
	AuthGroups   sql.NullString   `json:"auth_groups"`
	Sites        sql.NullString   `json:"sites"`
	Clients      sql.NullString   `json:"clients"`
}

type Site struct {
	AccountID         int64            `json:"account_id"`
	SiteID            int64            `json:"site_id"`
	SiteName          string           `json:"site_name"`
	CreateDate        time.Time        `json:"create_date"`
	LastUpdate        time.Time        `json:"last_update"`
	RecordStatus      NullRecordStatus `json:"record_status"`
	Active            NullRecordStatus `json:"active"`
	Des               sql.NullString   `json:"des"`
	Description       sql.NullString   `json:"description"`
	OperateBy         sql.NullString   `json:"operate_by"`
	Logo              sql.NullString   `json:"logo"`
	RulesDocuments    sql.NullString   `json:"rules_documents"`
	ServicesAmentiles sql.NullString   `json:"services_amentiles"`
	Type              sql.NullString   `json:"type"`
	Email             sql.NullString   `json:"email"`
	Phone             sql.NullString   `json:"phone"`
	Address           sql.NullString   `json:"address"`
	Website           sql.NullString   `json:"website"`
	Geolocation       sql.NullString   `json:"geolocation"`
}

type User struct {
	AccountID      int64            `json:"account_id"`
	UserID         int64            `json:"user_id"`
	CreateDate     sql.NullTime     `json:"create_date"`
	LastUpdate     sql.NullTime     `json:"last_update"`
	RecordStatus   NullRecordStatus `json:"record_status"`
	Active         NullRecordStatus `json:"active"`
	Identification sql.NullString   `json:"identification"`
	Password       string           `json:"password"`
	CompanyName    sql.NullString   `json:"company_name"`
	FirstName      string           `json:"first_name"`
	LastName       string           `json:"last_name"`
	Email          string           `json:"email"`
	Phone          sql.NullString   `json:"phone"`
	Emergencyphone sql.NullString   `json:"emergencyphone"`
	I18n           sql.NullString   `json:"i18n"`
	Address        sql.NullString   `json:"address"`
	AuthMenu       sql.NullString   `json:"auth_menu"`
	AuthKeys       sql.NullString   `json:"auth_keys"`
	AuthGroups     sql.NullString   `json:"auth_groups"`
	Sites          sql.NullString   `json:"sites"`
	Clients        sql.NullString   `json:"clients"`
}
