// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"context"
)

type Querier interface {
	GetConnectionID(ctx context.Context, userID int64) (Connection, error)
	UpdateConnection(ctx context.Context, arg UpdateConnectionParams) (Connection, error)
}

var _ Querier = (*Queries)(nil)
